name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release Name
        uses: actions/github-script@v7
        with:
          script: |
            const tagName = context.ref.substring(context.ref.lastIndexOf('/') + 2)
            core.exportVariable('RELEASE_NAME', tagName)

      - name: Zip Headers
        shell: bash
        run: |
          cd ..
          tar -czf modern-uuid-${{ env.RELEASE_NAME }}.tar.gz \
            --exclude='.*' \
            --exclude-vcs \
            --exclude-vcs-ignores \
            modern-uuid
          mv modern-uuid-${{ env.RELEASE_NAME }}.tar.gz modern-uuid
      
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            modern-uuid-${{ env.RELEASE_NAME }}.tar.gz

      